name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Resharper InspectCode
      uses: nbadal/inspectcode-action@v1
      with:
        # Path to your solution file, ex: MyProject.sln
        solution: ObservableGenerators.sln
    - name: Archive a nuget package
      uses: actions/upload-artifact@v2
      with:
        name: ObservableGenerators.nupkg
        path: ObservableGenerators/bin/Release/*.nupkg
    - name: Archive a inspction report
      uses: actions/upload-artifact@v2
      with:
        name: inspection-report.xml
        path: report.xml
